# Generated by Django 2.2.4 on 2019-08-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotify_link',
            field=models.TextField(default='https://www.spotify.com/'),
        ),
    ]
