# Generated by Django 2.2.4 on 2019-08-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.PositiveIntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_preview',
            field=models.TextField(default='https://www.spotify.com/'),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='untitled', max_length=100),
        ),
    ]
